import asyncio
import os
import json
from datasets import Dataset
from ragas import evaluate
from ragas.metrics import (
    context_precision,
    context_recall,
    answer_relevancy,
    faithfulness
)
# Make sure OPENAI_API_KEY is set in environment for standard RAGAS evaluation,
# or configure custom local LLMs via Langchain embeddings.

def run_evaluation(test_dataset_path: str, output_path: str):
    """
    Evaluates the RAG pipeline using Ragas framework.
    Requires a JSONL dataset containing:
    - question
    - answer (generated by our pipeline)
    - contexts (retrieved chunks)
    - ground_truth
    """
    print(f"Loading dataset from {test_dataset_path}")
    
    if not os.path.exists(test_dataset_path):
        print(f"Error: Dataset {test_dataset_path} not found. Please generate it first.")
        # Create a dummy dataset structure to guide the user
        dummy_data = {
            "question": ["What is the SLA?"],
            "answer": ["The SLA is 99.9% uptime."],
            "contexts": [["Our enterprise policy dictates a 99.9% SLA."]],
            "ground_truth": ["99.9% uptime"]
        }
        dataset = Dataset.from_dict(dummy_data)
        print("Using dummy dataset for demonstration.")
    else:
        with open(test_dataset_path, "r") as f:
            data = json.load(f)
        dataset = Dataset.from_dict(data)

    print("Running Ragas evaluation pipeline...")
    # NOTE: By default Ragas uses OpenAI. To use vLLM/Ollama, you must inject custom llm/embeddings.
    result = evaluate(
        dataset,
        metrics=[
            context_precision,
            context_recall,
            faithfulness,
            answer_relevancy,
        ],
    )

    print("\n=== Evaluation Results ===")
    print(result)

    with open(output_path, "w") as f:
        # Convert result to pandas dataframe, then to json
        df = result.to_pandas()
        df.to_json(f, orient="records", indent=2)
        
    print(f"\nSaved detailed results to {output_path}")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Run Ragas Evaluation")
    parser.add_argument("--dataset", type=str, default="rag_test_dataset.json", help="Path to evaluation dataset")
    parser.add_argument("--output", type=str, default="rag_evaluation_results.json", help="Output path for results")
    args = parser.parse_args()
    
    run_evaluation(args.dataset, args.output)
